### ISSUE TITLE
Error with sidechain dihedrals

### ISSUE THREAD

**Issue by patwin2** [AG-Peter/encodermap#25]
Hi. I've installed encoder map and successfully run the trp cage example. I've also been able to run the dihedrals only version of encodermap on some of my own data. However, I've run into an error when trying out the diubiquitin example. I obtained the trajectories from kaggle and thay are in the data/diubi folder. Here's the code:

------------------------------------------------------------------------------------------------------
import copy
import locale
import os

import matplotlib.pyplot as plt
import MDAnalysis as md
import numpy as np
import tensorflow as tf

import encodermap as em

molname = "diubi"

# ######################### Load data #########################

# Data available at:
# https://www.kaggle.com/andrejberg/md-simulations-of-linear-ubiquitin-dimers

structure_path = "data/{}/01.pdb".format(molname)
trajectory_paths = ["data/{}/{:02d}.xtc".format(molname, i + 1) for i in range(12)]

uni = md.Universe(structure_path, trajectory_paths)

# select only atoms in the backbone or directly bound to the backbone. Atoms in the side chains are not supported (yet)
selected_atoms = uni.select_atoms(
    "backbone or name H or name O1 or (name CD and resname PRO)"
)

# The MolData object takes care of calculating all the necessary information like dihedrals, angles, bondlengths ...
# You can provide a cache_path to store this information for the next time.
moldata = em.MolData(selected_atoms, cache_path="data/{}/cache".format(molname))

# ######################### Define parameters #########################

total_steps = 50000

# First we want to train without C_alpha cost.
# Finally, we want to activate the C_alpha cost to improve the long-range order of the generated conformations
parameters = em.ADCParameters()
parameters.main_path = em.misc.run_path("runs/{}".format(molname))

parameters.cartesian_cost_scale = 0
parameters.cartesian_cost_variant = "mean_abs"
parameters.cartesian_cost_scale_soft_start = (
    int(total_steps / 10 * 9),
    int(total_steps / 10 * 9) + 1000,
)
parameters.cartesian_pwd_start = (
    1  # Calculate pairwise distances starting form the second backbone atom ...
)
parameters.cartesian_pwd_step = 3  # for every third atom. These are the C_alpha atoms

parameters.dihedral_cost_scale = 1
parameters.dihedral_cost_variant = "mean_abs"

parameters.distance_cost_scale = 0  # no distance cost in dihedral space
parameters.cartesian_distance_cost_scale = (
    100  # instead we use distance cost in C_alpha distance space
)
parameters.cartesian_dist_sig_parameters = [400, 10, 5, 1, 2, 5]

parameters.checkpoint_step = max(1, int(total_steps / 10))
parameters.l2_reg_constant = 0.001
parameters.center_cost_scale = 0
parameters.id = molname

# ########### Check how distances are mapped with your choice of Sigmoid parameters ##################

pwd = em.misc.pairwise_dist(
    moldata.central_cartesians[
        ::1000, parameters.cartesian_pwd_start :: parameters.cartesian_pwd_step
    ],
    flat=True,
)
with tf.Session() as sess:
    pwd = sess.run(pwd)
axes = em.plot.distance_histogram(
    pwd, float("inf"), parameters.cartesian_dist_sig_parameters
)
plt.savefig('July_Histogram.png')
# somehow matplotlib messes with this setting and causes problems in tensorflow
locale.setlocale(locale.LC_NUMERIC, "en_US.UTF-8")

# ######################### Get references from dummy model #########################
dummy_parameters = copy.deepcopy(parameters)
dummy_parameters.main_path = em.misc.create_dir(
    os.path.join(parameters.main_path, "dummy")
)
dummy_parameters.n_steps = int(len(moldata.dihedrals) / parameters.batch_size)
dummy_parameters.summary_step = 1

e_map = em.AngleDihedralCartesianEncoderMapDummy(dummy_parameters, moldata)
e_map.train()
e_map.close()
e_map = None

costs = em.misc.read_from_log(
    os.path.join(dummy_parameters.main_path, "train"),
    ["cost/angle_cost", "cost/dihedral_cost", "cost/cartesian_cost"],
)
means = [np.mean(cost[:, 2]) for cost in costs]
parameters.angle_cost_reference = means[0]
parameters.dihedral_cost_reference = means[1]
parameters.cartesian_cost_reference = means[2]

np.savetxt(
    os.path.join(dummy_parameters.main_path, "adc_cost_means.txt"), np.array(means)
)

# ######################### Run Training #########################

# First run without C_alpha cost
parameters.n_steps = parameters.cartesian_cost_scale_soft_start[0]
e_map = em.AngleDihedralCartesianEncoderMap(parameters, moldata)
e_map.train()
e_map.close()
e_map = None

# Now we turn on C_alpha cost and continue the training run
parameters.n_steps = total_steps - parameters.cartesian_cost_scale_soft_start[0]
parameters.cartesian_cost_scale = 1
ckpt_path = os.path.join(
    parameters.main_path,
    "checkpoints",
    "step{}.ckpt".format(parameters.cartesian_cost_scale_soft_start[0]),
)

e_map = em.AngleDihedralCartesianEncoderMap(
    parameters, moldata, checkpoint_path=ckpt_path
)
e_map.train()
e_map.close()
e_map = None
------------------------------------------------------------------------------------------------------------

When I run this I get the following output:

-----------------------------------------------------------------------------------------------------------
2023-07-18 16:55:46.450274: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-18 16:55:46.558901: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-07-18 16:55:46.910422: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/pwintrod/anaconda3/envs/encodermap/lib/
2023-07-18 16:55:46.910472: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/pwintrod/anaconda3/envs/encodermap/lib/
2023-07-18 16:55:46.910479: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loaded cartesians from data/diubi/cache
Loaded dihedrals from data/diubi/cache
Calculating sidedihedrals...
:-1: UserWarning:  This version of the MolData Class does not produce expected results for side-dihedrals.
:-1: UserWarning:  To make this class work the 'residue_atoms[n:int(n+4)]' needs to be reworked. It does not index the sidechains.
Traceback (most recent call last):
  File "/home/pwintrod/anaconda3/envs/encodermap/lib/python3.9/site-packages/encodermap/encodermap_tf1/moldata.py", line 192, in __init__
    self.sidedihedrals = np.load(os.path.join(cache_path, "sidedihedrals.npy"))
  File "/home/pwintrod/anaconda3/envs/encodermap/lib/python3.9/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/diubi/cache/sidedihedrals.npy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pwintrod/EncoderMap/July_test.py", line 32, in <module>
    moldata = em.MolData(selected_atoms, cache_path="data/{}/cache".format(molname))
  File "/home/pwintrod/anaconda3/envs/encodermap/lib/python3.9/site-packages/encodermap/encodermap_tf1/moldata.py", line 225, in __init__
    sidedihedrals = Dihedral(sidedihedral_atoms, verbose=True).run(
  File "/home/pwintrod/anaconda3/envs/encodermap/lib/python3.9/site-packages/MDAnalysis/analysis/dihedrals.py", line 298, in __init__
    raise ValueError("All AtomGroups must contain 4 atoms")
ValueError: All AtomGroups must contain 4 atoms
----------------------------------------------------------------------------------------------------------------

There seems to be some problem with how the dihedrals are being defined. Any suggestions?

Thanks for your help.

**Comment by kevinsawade** [comment]
Hello patwin2,

I will look into your issue with EncoderMap. I can read from your code examples, that you are still using the old version of EncoderMap. Keep in mind, that the version of EncoderMap, which is available via `pip install encodermap` still uses an old version of tensorflow (>2.0), which is bound to be deprecated at some point. You can install the newer version of EncoderMap via `pip install git+https://github.com/AG-Peter/encodermap.git`. With the new version, you have backwards-compatibility with `import encodermap.encodermap_tf1 as em` and can keep your old code.

That being said, I ran into the same `ValueError` as you with the backwards-compatible version:

```python
import sys
import tensorflow as tf
import encodermap.encodermap_tf1 as em
import MDAnalysis as mda
print(f"Info: {sys.version=}, {tf.__version__=}")

# uncomment to download the data
# import kaggle
# kaggle.api.dataset_download_files(
#     "andrejberg/md-simulations-of-linear-ubiquitin-dimers",
#     path="/home/kevin/.kaggle/ubiquitin_dimers",
#     unzip=True,
# )

# define the data paths. this varies based on where you have the data stored
structure_path = "/home/kevin/.kaggle/ubiquitin_dimers/01.pdb"
trajectory_paths = [f"/home/kevin/.kaggle/ubiquitin_dimers/{i:02d}.xtc" for i in range(1, 13)]

# create MDAnalysis universe
uni = mda.Universe(structure_path, trajectory_paths)
selected_atoms = uni.select_atoms("backbone or name H or name O1 or (name CD and resname PRO)")
moldata = em.MolData(selected_atoms, cache_path="/home/kevin/.kaggle/ubiquitin_dimers/moldata_cacge")
```

Output:
```
Info: sys.version='3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) \n[GCC 10.3.0]', tf.__version__='2.8.1'
Loading Cartesians...
100%|██████████| 60012/60012 [00:14<00:00, 4189.01it/s]
Calculating dihedrals...
100%|██████████| 60012/60012 [00:30<00:00, 1952.58it/s]
/home/kevin/anaconda3/envs/py39_tf2/lib/python3.9/site-packages/MDAnalysis/analysis/dihedrals.py:337: DeprecationWarning: The `angle` attribute was deprecated in MDAnalysis 2.0.0 and will be removed in MDAnalysis 3.0.0. Please use `results.angles` instead
  warnings.warn(wmsg, DeprecationWarning)
Calculating sidedihedrals...
:-1: UserWarning:  This version of the MolData Class does not produce expected results for side-dihedrals.
:-1: UserWarning:  To make this class work the 'residue_atoms[n:int(n+4)]' needs to be reworked. It does not index the sidechains.
Traceback (most recent call last):
  File "/home/kevin/git/encoder_map_private/encodermap/encodermap_tf1/moldata.py", line 192, in __init__
    self.sidedihedrals = np.load(os.path.join(cache_path, "sidedihedrals.npy"))
  File "/home/kevin/anaconda3/envs/py39_tf2/lib/python3.9/site-packages/numpy/lib/npyio.py", line 390, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/kevin/.kaggle/ubiquitin_dimers/moldata_cacge/sidedihedrals.npy'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/kevin/anaconda3/envs/py39_tf2/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3433, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-46f41fa3dd48>", line 22, in <module>
    moldata = em.MolData(selected_atoms, cache_path="/home/kevin/.kaggle/ubiquitin_dimers/moldata_cacge")
  File "/home/kevin/git/encoder_map_private/encodermap/encodermap_tf1/moldata.py", line 225, in __init__
    sidedihedrals = Dihedral(sidedihedral_atoms, verbose=True).run(
  File "/home/kevin/anaconda3/envs/py39_tf2/lib/python3.9/site-packages/MDAnalysis/analysis/dihedrals.py", line 313, in __init__
    raise ValueError("All AtomGroups must contain 4 atoms")
ValueError: All AtomGroups must contain 4 atoms
```

**Comment by kevinsawade** [comment]
The new version should fix this issue. Please update with:

```bash
pip install --upgrade git+https://github.com/AG-Peter/encodermap.git
```

Reopen the issue, if the error persists.

**Comment by patwin2** [comment]
So I tried

"pip install --upgrade git+https://github.com/AG-Peter/encodermap.git"

as suggested, but I still get the same error message (I updated pip prior to trying).

For reference, here is the yml file for the environment I'm working in. Are any package versions obviously wrong?

---------------------------------------------------------------------------------------------------
name: encodermap
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.5.7=hbcca054_0
  - cudatoolkit=11.4.2=h7a5bcfd_11
  - cudnn=8.2.1.32=h86fa8c9_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgomp=12.2.0=h65d4601_19
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.42.0=h2797004_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=h166bdaf_4
  - ncurses=6.3=h27087fc_1
  - openssl=3.1.0=hd590300_3
  - python=3.9.16=h2782a2a_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=67.7.2=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
    - absl-py==1.4.0
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - astunparse==1.6.3
    - attrs==23.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - biopython==1.81
    - bleach==6.0.0
    - cachetools==5.3.0
    - certifi==2023.5.7
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - click==8.1.3
    - cloudpickle==2.2.1
    - comm==0.1.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - dask==2023.5.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - deeptime==0.4.4
    - defusedxml==0.7.1
    - dill==0.3.6
    - distributed==2023.5.0
    - encodermap==3.0.0
    - executing==1.2.0
    - fast-histogram==0.11
    - fasteners==0.18
    - fastjsonschema==2.16.3
    - flatbuffers==23.5.9
    - fonttools==4.39.4
    - fqdn==1.5.1
    - fsspec==2023.5.0
    - gast==0.4.0
    - google-auth==2.18.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - griddataformats==1.0.1
    - grpcio==1.54.2
    - gsd==2.8.1
    - h5netcdf==1.1.0
    - h5py==3.8.0
    - humanfriendly==10.0
    - idna==3.4
    - importlib-metadata==6.6.0
    - importlib-resources==5.12.0
    - ipykernel==6.23.1
    - ipython==8.13.2
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.5
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-client==8.2.0
    - jupyter-core==5.3.0
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.4
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.4
    - libclang==16.0.0
    - llvmlite==0.40.0
    - locket==1.0.0
    - markdown==3.4.3
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mdanalysis==2.4.3
    - mdshare==0.4.2
    - mdtraj==1.9.7
    - mistune==2.0.5
    - mmtf-python==1.1.3
    - mpl-scatter-density==0.7
    - mrcfile==1.4.3
    - msgpack==1.0.5
    - multiprocess==0.70.14
    - nbclassic==1.0.0
    - nbclient==0.7.4
    - nbconvert==7.4.0
    - nbformat==5.8.0
    - nest-asyncio==1.5.6
    - networkx==3.1
    - nglview==3.0.4
    - notebook==6.5.4
    - notebook-shim==0.2.3
    - numba==0.57.0
    - numpy==1.24.3
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - packaging==23.1
    - pandas==2.0.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - partd==1.4.0
    - pathos==0.3.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.3.0
    - pip==23.2.1
    - platformdirs==3.5.1
    - pox==0.3.2
    - ppft==1.7.6.6
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - protobuf==3.19.6
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pyemma==2.5.12
    - pygments==2.15.1
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - pytz==2023.3
    - pyyaml==6.0
    - pyzmq==25.0.2
    - requests==2.30.0
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.9
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - seaborn==0.12.2
    - send2trash==1.8.2
    - six==1.16.0
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - soupsieve==2.4.1
    - stack-data==0.6.2
    - tblib==1.7.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.10.0
    - tensorflow-estimator==2.10.0
    - tensorflow-io-gcs-filesystem==0.32.0
    - termcolor==2.3.0
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - toolz==0.12.0
    - tornado==6.3.2
    - tqdm==4.65.0
    - traitlets==5.9.0
    - typing-extensions==4.5.0
    - tzdata==2023.3
    - uri-template==1.2.0
    - urllib3==1.26.15
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - werkzeug==2.3.4
    - widgetsnbextension==3.6.4
    - wrapt==1.15.0
    - xarray==2023.4.2
    - zict==3.0.0
    - zipp==3.15.0
prefix: /home/pwintrod/anaconda3/envs/encodermap
-----------------------------------------------------------------------------------------

Thanks.
